In [3]:
import numpy as np
from scipy.sparse.linalg import svds

# Sample User-Item Interaction Matrix
R = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4],
])

# Mean normalization
user_ratings_mean = np.mean(R, axis=1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)

# Perform SVD
U, sigma, Vt = svds(R_demeaned, k=2)

# Convert sigma to a diagonal matrix
sigma = np.diag(sigma)

# Reconstruct the ratings matrix
predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)

print("Original User-Item Interaction Matrix:\n", R)
print("\nPredicted Ratings:\n", np.round(predicted_ratings, 2))


Original User-Item Interaction Matrix:
 [[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]]

Predicted Ratings:
 [[ 5.1   2.82  0.09  0.99]
 [ 3.24  1.35 -0.71  1.11]
 [ 1.3   0.47  0.28  4.96]
 [ 0.92  0.15 -0.08  4.01]
 [-0.45  1.81  4.58  4.07]]


In [11]:
import pandas as pd

# Specify the path to your CSV file
csv_file_path = 'steam-200k.csv'  # Change this to your file path

# Read the CSV file into a DataFrame
data = pd.read_csv(csv_file_path)
data.columns = ['ID', 'Game', 'Stat', 'Play Time', 'N']
data.drop(columns=['N'], inplace=True)
# Display the first few rows of the DataFrame
print(len(set(data["ID"])))


12393
