In [ ]:
import numpy as np

# Sample user-item rating matrix
R = np.array([[5, 3, 0, 1],
              [4, 0, 0, 1],
              [1, 1, 0, 5],
              [1, 0, 0, 4],
              [0, 1, 5, 4]])


In [ ]:
def mean_normalize(R):
    """Mean normalize the ratings matrix."""
    R_mean = np.mean(R, axis=1).reshape(-1, 1)
    R_normalized = R - R_mean
    return R_normalized, R_mean

In [ ]:

def perform_svd(R_normalized):
    """Perform Singular Value Decomposition."""
    U, sigma, Vt = np.linalg.svd(R_normalized, full_matrices=False)
    return U, sigma, Vt

In [ ]:
def select_top_k(U, sigma, Vt, k):
    """Select the top k singular values and corresponding vectors."""
    U_k = U[:, :k]
    sigma_k = np.diag(sigma[:k])
    Vt_k = Vt[:k, :]
    return U_k, sigma_k, Vt_k

In [ ]:
def reconstruct_matrix(U_k, sigma_k, Vt_k, R_mean):
    """Reconstruct the original ratings matrix."""
    R_approx = np.dot(np.dot(U_k, sigma_k), Vt_k) + R_mean
    return R_approx

In [ ]:

def matrix_factorization(R, k):
    """Perform matrix factorization using SVD."""
    R_normalized, R_mean = mean_normalize(R)
    U, sigma, Vt = perform_svd(R_normalized)
    U_k, sigma_k, Vt_k = select_top_k(U, sigma, Vt, k)
    R_approx = reconstruct_matrix(U_k, sigma_k, Vt_k, R_mean)
    return R_approx

# Parameters
k = 2  # Number of latent features

# Perform matrix factorization
R_approx = matrix_factorization(R, k)

print("Original Ratings Matrix:")
print(R)
print("\nApproximated Ratings Matrix:")
print(np.round(R_approx))


Original Ratings Matrix:
[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]]

Approximated Ratings Matrix:
[[ 5.  3.  0.  1.]
 [ 3.  1. -1.  1.]
 [ 1.  0.  0.  5.]
 [ 1.  0. -0.  4.]
 [-0.  2.  5.  4.]]


You take the user item matrix and then decompose it into the latent factors for the users and for the items.

You then will 